<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaoying Yang">
<meta name="dcterms.date" content="2023-11-25">

<title>xiaoyingyang96.github.io - Predicting Humidity Using Linear and Non-linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">xiaoyingyang96.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Xiaoying Yang</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/xiaoyingyang96" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="http://www.linkedin.com/in/xiaoying-yang-92110a156" rel="" target=""><i class="bi bi-LinkedIn" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Predicting Humidity Using Linear and Non-linear Regression</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">code</div>
                <div class="quarto-category">analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Xiaoying Yang </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 25, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="temperature-and-humidity" class="level1">
<h1>Temperature and Humidity</h1>
<p><img src="climatechange11.jpg" class="img-fluid"></p>
<p>Temperature and humidity are critical for weather forecasting and climate modeling. They affect agricultural production, building design, energy use etc. <a href="https://www.un.org/en/climatechange/what-is-climate-change">[1]</a> In the area of environmental science, understanding the relationship between temperature and humidity is critical in detecting changes in ecosystems, predicting weather patterns, and even assessing global climate change. Moreover, temperature and humidity based analysis can help develop more effective strategies and decisions for industries that need to consider environmental factors. Therefore, the prediction of climate information is a topic of interests that has been analyzed through a long period. Machine Learning, a powerful tool in dealing large datasets, is expected to provide a more precise climate prediction than ever before.</p>
<p>In this blog, we explore the application of machine learning algorithms for linear and non-linear regression, focusing on predicting humidity based on average daily temperature. We will employ the Lasso algorithm for linear regression and leverage Support Vector Regression(SVR) for the non-linear regression analysis. Through a comparative analysis of linear and non-linear regression results, this blog illustrates how machine learning algorithms can be effectively utilized in climate prediction scenarios.</p>
</section>
<section id="about-the-dataset" class="level1">
<h1>About the Dataset</h1>
<p>This blog explores the application of regressions through a comprehensive dataset, capturing climate data from January 1, 2013, to April 24, 2017, in Delhi, India. <a href="https://www.kaggle.com/datasets/sumanthvrao/daily-climate-time-series-data">[2]</a> Our focus is to unravel the intricate relationship between temperature and humidity using this detailed dataset. The scatter plot shows the relationship between temperature and humidity in the training data. It appears there might be some non-linear relationship between these two variables. Nevertheless, we will conduct both linear and regression to explore the relationship between temperature and humidity.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.svm <span class="im">import</span> SVR</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error, r2_score</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Functions for loading and pre-processing data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> load_and_preprocess_data(file_path):</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    data <span class="op">=</span> pd.read_csv(file_path)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> data</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># load training &amp; test dataset</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>train_data_path <span class="op">=</span> <span class="st">'https://raw.githubusercontent.com/xiaoyingyang96/xiaoyingyang96.github.io/main/Data/DailyDelhiClimateTrain.csv'</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>test_data_path <span class="op">=</span> <span class="st">'https://raw.githubusercontent.com/xiaoyingyang96/xiaoyingyang96.github.io/main/Data/DailyDelhiClimateTest.csv'</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>train_data <span class="op">=</span> load_and_preprocess_data(train_data_path)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>test_data <span class="op">=</span> load_and_preprocess_data(test_data_path)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Define features as daily avg temperature. Define target as humidity</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>features <span class="op">=</span> [<span class="st">'meantemp'</span>]</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">'humidity'</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare training and test data</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> train_data[features]</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> train_data[target]</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> test_data[features]</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> test_data[target]</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the relationship between temperature and humidity in the training data</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span> <span class="st">'meantemp'</span>, y<span class="op">=</span><span class="st">'humidity'</span>,data <span class="op">=</span> train_data)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relationship between Temperature and Humidity (Training Data)'</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Temperature (°C)'</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Humidity (%)'</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-2-output-1.png" width="818" height="523"></p>
</div>
</div>
</section>
<section id="linear-regression-least-absolute-shrinkage-and-selection-operator-lasso" class="level1">
<h1>Linear Regression: Least Absolute Shrinkage and Selection Operator (Lasso)</h1>
<p>In statistics and machine learning, Lasso (least absolute shrinkage and selection operator) is a regression analysis method that performs both variable selection and regularization in order to enhance the prediction accuracy and interpretability of the resulting statistical model. In this blog, we employed Lasso to conduct the linear regression analysis to predict the humidity based on average daily temperature.</p>
<p>Here are main steps in apply Lasso:</p>
<p><strong>1. Data Preparation:</strong> load data, clean data, choose relevant features for the regression, and split data into training and testing sets.</p>
<p><strong>2. Feature Scaling</strong>: Lasso is sensitive to the scale of input features, so it’s a good practice to standardize or normalize features.</p>
<p><strong>3. Model creation and training</strong>: Instantiate a Lasso object, choose an alpha value which controls the degree of shrinkage, and train the model on training dataset.</p>
<p><strong>4. Model evaluation</strong>: Common metrics for regression include MSE, Root Mean Squared Error (RMSE), and R-squared (R^2)</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Lasso</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the data</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>X_train_scaled <span class="op">=</span> scaler.fit_transform(X_train)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>X_test_scaled <span class="op">=</span> scaler.transform(X_test)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Lasso regression model</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>lasso_model <span class="op">=</span> Lasso(alpha<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>lasso_model.fit(X_train_scaled, y_train)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>y_train_pred_lasso <span class="op">=</span> lasso_model.predict(X_train_scaled)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>y_test_pred_lasso <span class="op">=</span> lasso_model.predict(X_test_scaled)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the lasso model</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>lasso_train_rmse <span class="op">=</span> mean_squared_error(y_train, y_train_pred_lasso, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>lasso_test_rmse <span class="op">=</span> mean_squared_error(y_test, y_test_pred_lasso, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>lasso_train_r2 <span class="op">=</span> r2_score(y_train, y_train_pred_lasso)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>lasso_test_r2 <span class="op">=</span> r2_score(y_test, y_test_pred_lasso)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a DataFrame to display the Lasso model results</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>lasso_results <span class="op">=</span> {</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Metric"</span>: [<span class="st">"Lasso RMSE (Training Data)"</span>, <span class="st">"Lasso RMSE (Testing Data)"</span>, <span class="st">"Lasso R² (Training Data)"</span>, <span class="st">"Lasso R² (Testing Data)"</span>],</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>: [lasso_train_rmse, lasso_test_rmse, lasso_train_r2, lasso_test_r2]</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>lasso_results_df <span class="op">=</span> pd.DataFrame(lasso_results)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>lasso_results_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Lasso RMSE (Training Data)</td>
<td>13.751603</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Lasso RMSE (Testing Data)</td>
<td>15.788514</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Lasso R² (Training Data)</td>
<td>0.327092</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Lasso R² (Testing Data)</td>
<td>0.308337</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="evaluation-of-lasso-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="evaluation-of-lasso-regression-analysis">Evaluation of Lasso Regression Analysis</h2>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># LASSO: Plot scatter and regression diagram</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(train_data[<span class="st">'meantemp'</span>], train_data[<span class="st">'humidity'</span>], color<span class="op">=</span><span class="st">'blue'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Actual humidity (train data)'</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>plt.plot(train_data[<span class="st">'meantemp'</span>], y_train_pred_lasso, color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'Estimated humidity(train data)'</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>plt.scatter(test_data[<span class="st">'meantemp'</span>], test_data[<span class="st">'humidity'</span>], color<span class="op">=</span><span class="st">'green'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Actual humidity (test data)'</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>plt.plot(test_data[<span class="st">'meantemp'</span>], y_test_pred_lasso, color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'Estimated humidity(test data)'</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Daily Average Temperature (°C)'</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Humidity(%)'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Daily Average Temperatrue vs Humidity(Actual vs Estimated)'</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-4-output-1.png" width="818" height="523"></p>
</div>
</div>
<p>Mean Squared Error is a measure of the average of the squares of the errors or deviations. In simpler terms, it calculates the average squared difference between the estimated values and the actual value. The RMSE values indicate the average magnitude of the errors in predicting humidity from temperature, thus a lower RMSE value is better.</p>
<p><span class="math display">\[ RMSE =\sqrt{\frac{1}{n}\sum_{i=1}^{n}(Y_i-\hat{Y}_i)^2} \]</span></p>
<p>RMSE = Root mean squared error</p>
<p>n = number of data points</p>
<p><span class="math inline">\(Y_i\)</span>=Observed values</p>
<p><span class="math inline">\(\hat{Y}_i\)</span> = Predicted values</p>
<p>The Coefficient of Determination, often denoted as R², is a statistical measure that represents the proportion of variance for the dependent variable that’s explained by the independent variables in a regression model.</p>
<p><span class="math display">\[ R^2 = 1-\frac{RSS}{TSS} \]</span></p>
<p><span class="math inline">\(R^2\)</span> = coefficient of determination</p>
<p>RSS= sum of squares of residuals. It is the sum of the squared differences between actual and predicted values.</p>
<p>TSS = total sum of squares. It is the sum of the squared differences from the mean of the actual values.</p>
<p>In this study, the RMSE of 13.75 on the training data and 15.79 on the testing data suggests moderate errors in the model’s predictions. The higher RMSE on the testing data compared to the training data may indicate a slight overfitting to the training data or a difference in the distribution of the training and testing sets.</p>
<p>In lasso regression model. the R² values in both the training (0.33) and testing (0.31) datasets are relatively low. This indicates that 33% of the variance in humidity is explained by temperature in the training set, and about 31% in the testing set. These indexes suggest that temperature alone may not be sufficient to accurately predict humidity, or that the relationship between temperature and humidity is not strongly linear.</p>
<p>In conclusion, the model’s performance is moderate. More relevant features are expected to apply in the model to make a better prediction of humidity.</p>
</section>
</section>
<section id="non-linear-regression-supported-vector-regression" class="level1">
<h1>Non-linear Regression: Supported Vector Regression</h1>
<p>Support Vector Regression (SVR) is a type of machine learning algorithm that falls under the category of Support Vector Machines (SVM). Instead of finding a hyperplane to separate two classes, SVR algorithm tries to fit the best line within a threshold value. This line is the decision boundary that minimizes the error within a certain tolerance level, known as the ε-tube.</p>
<p>SVR is highly effective in capturing complex, non-linear relationships between data points, which is common in many real-world scenarios. Due to its margin of tolerance, SVR can be more robust to outliers compared to other regression methods. It focuses on the most critical data points (support vectors) and is less influenced by outliers. Here are steps for applying SVR algorithm:</p>
<ol type="1">
<li><strong>Data collection and preprocessing</strong>: Collect relevant data, and clean the data by handling missing values, outliers, and possibly normalizing or scaling the features.</li>
<li><strong>Feature selection and engineering</strong>: Identify and select the most relevant features that contribute to the output variable. Then, transform existing features to better capture the underlying patterns in the data.</li>
<li><strong>Kernel Selection</strong>: SVR can use various types of kernels (like linear, polynomial, radial basis function). The choice of kernel depends on the nature of the data and the relationship between the features and the target variable.</li>
<li><strong>Model configuration</strong>: Tune parameters in SVR including C(regularization parameter), epsilon (margin of tolerance), and kernel-specific parameters. These need to be tuned to find the best combination for your model.</li>
<li><strong>Train the model</strong>: Use the training data to train the SVR model. This involves finding the best fitting hyperplane that minimizes the error within the defined margin.</li>
<li><strong>Model Evaluation</strong>: Assess the model’s performance using metrics such as mean squared error(MSE), R-squared, etc. Evaluate the model on a validation set or through cross-validation techniques to gauge its performance on unseen data.</li>
<li><strong>Prediction and interpretation</strong>: Use the trained model to make predictions on new or test data. Interpret the results in the context of the problem domain. Understand the implication of the predictions and the model’s limitations.</li>
</ol>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.svm <span class="im">import</span> SVR</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Reusing the loaded train and test data</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> train_data[[<span class="st">'meantemp'</span>]].values</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>y_train <span class="op">=</span> train_data[<span class="st">'humidity'</span>].values</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>X_test <span class="op">=</span> test_data[[<span class="st">'meantemp'</span>]].values</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>y_test <span class="op">=</span> test_data[<span class="st">'humidity'</span>].values</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardizing the data</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>X_train_scaled <span class="op">=</span> scaler.fit_transform(X_train)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>X_test_scaled <span class="op">=</span> scaler.transform(X_test)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># SVR model for non-linear regression</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>svr_model <span class="op">=</span> SVR(kernel<span class="op">=</span><span class="st">'rbf'</span>)  <span class="co"># Using Radial Basis Function (RBF) kernel</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>svr_model.fit(X_train_scaled, y_train)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictions</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>y_train_pred_svr <span class="op">=</span> svr_model.predict(X_train_scaled)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>y_test_pred_svr <span class="op">=</span> svr_model.predict(X_test_scaled)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the SVR model</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>svr_train_rmse <span class="op">=</span> mean_squared_error(y_train, y_train_pred_svr, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>svr_test_rmse <span class="op">=</span> mean_squared_error(y_test, y_test_pred_svr, squared<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>svr_train_r2 <span class="op">=</span> r2_score(y_train, y_train_pred_svr)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>svr_test_r2 <span class="op">=</span> r2_score(y_test, y_test_pred_svr)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a DataFrame to display the SVR model results</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>svr_results <span class="op">=</span> {</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Metric"</span>: [<span class="st">"SVR RMSE (Training Data)"</span>, <span class="st">"SVR RMSE (Testing Data)"</span>, <span class="st">"SVR R² (Training Data)"</span>, <span class="st">"SVR R² (Testing Data)"</span>],</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Value"</span>: [svr_train_rmse, svr_test_rmse, svr_train_r2, svr_test_r2]</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>svr_results_df <span class="op">=</span> pd.DataFrame(svr_results)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>svr_results_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Metric</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>SVR RMSE (Training Data)</td>
<td>12.993213</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>SVR RMSE (Testing Data)</td>
<td>17.372828</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>SVR R² (Training Data)</td>
<td>0.399266</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>SVR R² (Testing Data)</td>
<td>0.162561</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="results-evaluation-of-svr-model" class="level2">
<h2 class="anchored" data-anchor-id="results-evaluation-of-svr-model">Results Evaluation of SVR Model</h2>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SVR: Plot scatter and regression diagram</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>plt.scatter(train_data[<span class="st">'meantemp'</span>], train_data[<span class="st">'humidity'</span>], color<span class="op">=</span><span class="st">'blue'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Actual humidity (train data)'</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>plt.plot(train_data[<span class="st">'meantemp'</span>], y_train_pred_svr, color<span class="op">=</span><span class="st">'red'</span>, label<span class="op">=</span><span class="st">'Estimated humidity(train data)'</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>plt.scatter(test_data[<span class="st">'meantemp'</span>], test_data[<span class="st">'humidity'</span>], color<span class="op">=</span><span class="st">'green'</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, label<span class="op">=</span><span class="st">'Actual humidity (test data)'</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>plt.plot(test_data[<span class="st">'meantemp'</span>], y_test_pred_svr, color<span class="op">=</span><span class="st">'orange'</span>, label<span class="op">=</span><span class="st">'Estimated humidity(test data)'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Daily Average Temperature (°C)'</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Humidity(%)'</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Daily Average Temperatrue vs Humidity(Actual vs Estimated)'</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="index_files/figure-html/cell-6-output-1.png" width="818" height="523"></p>
</div>
</div>
<p>The RMSE for the training data is 12.99, which is slightly better than the RMSE for the Lasso model. The RMSE for the testing data is 17.37, which is higher than that of the training data and also higher compared to the Lasso model. This indicates that the model may not generalize as well to new, unseen data.</p>
<p>The R² value on the training data is 0.40, suggesting the model explains 40% of the variance in humidity based on temperature, which is an improvement over the Lasso model. The R² value on the testing data is 0.16, much lower than the training data, indicating a significant drop in model performance on unseen data.</p>
</section>
</section>
<section id="general-observation-of-regression-models" class="level1">
<h1>General Observation of Regression Models</h1>
<p>Based on the SVR model’s performance, it is evident that while the model shows some improvement in fitting the training data compared to the Lasso model, it demonstrates a notably lower performance on the testing data. This is highlighted by the higher RMSE (Root Mean Squared Error) and the lower R² (R-squared) values on the testing dataset. Specifically, the RMSE for the testing data is significantly higher than that for the training data, indicating that the predictions of the model are less accurate when exposed to new, unseen data. This discrepancy suggests a potential overfitting issue, where the model is too closely tailored to the specifics of the training data, at the expense of its ability to generalize to new data.</p>
<p>The R² values further reinforce this point. While the SVR model explains about 40% of the variance in the training data, its explanatory power drops substantially in the testing data, as indicated by the much lower R² value. This drop in performance on unseen data is a classic indication of overfitting. Overfitting is a common challenge in machine learning, especially with more complex models like SVR, which can capture intricate patterns in the data. However, if these patterns are too specific to the training set, they may not apply well to other datasets, leading to poorer performance on new data.</p>
<p>To address these issues, further tuning of the SVR model's parameters might be necessary. Parameters such as the kernel type, C (regularization parameter), and epsilon (margin of tolerance in the regression) play critical roles in the model’s ability to balance complexity and generalization. Adjusting these parameters could help in finding a better compromise between fitting the training data well and maintaining robustness on new data. Moreover, incorporating additional features or exploring different feature transformations could also be beneficial in enhancing the model’s predictive power and its generalization ability.</p>
<p>In fact, the relationship between temperature and humidity is complex due to the way heat affects air and its capacity to hold moisture. Warmer air has a greater capacity to hold water vapor compared to cooler air, as the increase in temperature energizes water molecules, allowing more to exist in a gaseous state. This means that as temperature rises, if the moisture content remains constant, the relative humidity – which is the amount of moisture in the air relative to what it can hold at that temperature – actually decreases. However, this interaction varies greatly depending on geographic location, climate, and seasonal changes. For instance, in tropical regions, high temperatures often coincide with high humidity, creating a muggy climate, while in deserts, high temperatures pair with low humidity.</p>
<p>Despite the observed limitations in using linear and non-linear regression models to predict humidity from temperature data, it remains a valuable tool for deciphering large datasets and making informed predictions. Its potential becomes particularly promising with future adjustments and refinements to the model. This approach not only aids in understanding complex data relationships but also holds significant promise for more accurate and reliable forecasting once model optimization are implemented.</p>
</section>
<section id="reference" class="level1">
<h1>Reference</h1>
<ol type="1">
<li>https://www.un.org/en/climatechange/what-is-climate-change</li>
<li>https://www.kaggle.com/datasets/sumanthvrao/daily-climate-time-series-data</li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>